use_frameworks!

platform :ios, '9.0'

target 'YLZ-NetEncryption-iOS_Example' do
  pod 'YLZ-NetEncryption-iOS', :path => '../'

  target 'YLZ-NetEncryption-iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
